[project]
name = "ae2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "xerachrrm", email = "xerachrrm@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ae2 = "ae2:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "zensical>=0.0.68",
]
